input {
  # sqs {
  #   queue => "security-log-buffer-queue"
  #   region => "ap-northeast-2"
  # }
}

filter {
  # grok { ... }
}

output {
  opensearch {
    hosts => ["http://opensearch:9200"]
    index => "security-logs-%{+YYYY.MM.dd}"
  }
}
